###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "fistname":"akhil",
    "lastname":"v a",
    "email":"akhilva@gmail.com",
    "phone_number":"237612537",
    "date_of_birth":"2004-10-20",
    "gender":"male",
    "current_address":"valiyaveettil ,puthuvype,ernakulam-682508",
    "password":"gilgamesh@123",
    "prn_number":"123456789102",
    "graduation_year":2012,
    "degree_id":12,
    "department_id":2,
    "current_position":"senior developer",
    "company_name":"utech",
    "industry_id":3,
    "work_email":"akjji@gmail.com",
    "linkedin_profile":"https://ghsdygwd@linkedin.com",
    "key_skills":"kjkdwhck,jwdghjwdjh,kwhdcjge"
}