###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName":"ratheesh",
    "lastName":"e p",
    "email":"raathev2004@gmail.com",
    "phone":"9895344134",
    "dob":"2004-09-29",
    "gender":"female",
    "address":"uywegdjygduewdedwedwedwede",
    "password":"gilgamesh@123",
    "prn":"123456789115",
    "graduationYear":"2012",
    "degree":"1",
    "department":"2",
    "course":"2",
    "position":"senior developer",
    "company":"utech",
    "industry":"2",
    "workEmail":"dwjeder@gamil.com",
    "linkedin":"https://ghsdywrsd@linkedin.com",
    "skills":"kjkdwhck,jwdghjwdjh,kwhdcjge",
    "role":"ALUMNI"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"safaev2004@gmail.com",
    "password":"gilgamesh@123"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"raathev2004@gmail.com",
    "password":"gilgamesh@123"
}