###
GET http://localhost:5000/profile/miniprofile
headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFMVU1OSSIsImlhdCI6MTc1OTIzODM2NywiZXhwIjoxNzU5MjQxOTY3fQ.9HLzu0vrLP7cxyueJhjFYOcL6vsEX0RxkVcUH8EggzI

###
GET  http://localhost:5000/profile/fullprofile
headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFMVU1OSSIsImlhdCI6MTc1OTU3MjAwNywiZXhwIjoxNzU5NTc1NjA3fQ.DI1v80c2HN3TX07GoP_EFWTULEBQkd3tVnjt6zq2qpA
